name: openhands
services:
    openhands:
        stdin_open: true
        tty: true
        pull_policy: always
        environment:
            - SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:0.55-nikolaik
            - LOG_ALL_EVENTS=true
            - LLM_BASE_URL="http://host.docker.internal:8080" # use base url for custom api 
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ~/.openhands-state:/.openhands-state
        ports:
            - 3000:3000
        extra_hosts:
            - host.docker.internal:host-gateway
        container_name: openhands-app
        image: docker.all-hands.dev/all-hands-ai/openhands:0.55
